// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zuber.Models;

namespace Zuber.Migrations
{
    [DbContext(typeof(ZuberDBContext))]
    [Migration("20210504110248_almostFinal")]
    partial class almostFinal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Zuber.Models.Dot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Long")
                        .HasColumnType("float");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("ZuberUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZuberUserID");

                    b.ToTable("Dots");
                });

            modelBuilder.Entity("Zuber.Models.Passanger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RideID")
                        .HasColumnType("int");

                    b.Property<int>("ZuberUserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RideID");

                    b.HasIndex("ZuberUserID");

                    b.ToTable("Passangers");
                });

            modelBuilder.Entity("Zuber.Models.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentPassangers")
                        .HasColumnType("int");

                    b.Property<int>("MaxPassangers")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeToFromZealand")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ToZealand")
                        .HasColumnType("bit");

                    b.Property<int>("ZuberUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ZuberUser");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("Zuber.Models.ZuberUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Driver")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Zuber.Models.Dot", b =>
                {
                    b.HasOne("Zuber.Models.ZuberUser", "ZuberUser")
                        .WithMany()
                        .HasForeignKey("ZuberUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ZuberUser");
                });

            modelBuilder.Entity("Zuber.Models.Passanger", b =>
                {
                    b.HasOne("Zuber.Models.Ride", "Ride")
                        .WithMany()
                        .HasForeignKey("RideID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zuber.Models.ZuberUser", "ZuberUser")
                        .WithMany()
                        .HasForeignKey("ZuberUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");

                    b.Navigation("ZuberUser");
                });

            modelBuilder.Entity("Zuber.Models.Ride", b =>
                {
                    b.HasOne("Zuber.Models.ZuberUser", "Driver")
                        .WithMany()
                        .HasForeignKey("ZuberUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });
#pragma warning restore 612, 618
        }
    }
}
